Repository hyundai-fruitfruit/admin-front, pull requests merged in 2024-02, with the labels that each got.

#3 [Heendy-53-event-delete] 삭제기능 & 이벤트 등록시 쿠폰 선택 기능
  src/jsx/components/Cms/Content.jsx
  src/jsx/components/Cms/ContentAdd.jsx
  src/jsx/index.jsx
Labels: 💡 feature, 🔥 H-1, 🐻 가브리엘

#4 [Heendy-59-admin-event-level] 레벨 요소 추가 & API 분리 & 날짜 입력 버그 수정
  src/hooks/useCoupons.jsx
  src/hooks/useCreateEvent.jsx
  src/hooks/useEvents.jsx
  src/jsx/components/Cms/Content.jsx
  src/jsx/components/Cms/ContentAdd.jsx
  src/jsx/components/Cms/Menu.jsx
  src/jsx/index.css
  src/jsx/index.jsx
  src/jsx/layouts/nav/Deflayout.jsx
  src/jsx/layouts/nav/Menus2.jsx
  src/services/couponService.js
  src/services/eventService.js
Labels: 💡 feature, 🐞 fix, 🐻 가브리엘, 🐾 refactor

#5 feat: qrcode 인식 모달 페이지구현
  .env
  jsconfig.json
  package.json
  src/jsx/components/Cms/Content.jsx
  src/jsx/components/Modal/eventmodal/EventModal.jsx
  src/jsx/components/QrScanner/QRScannerComponent.jsx
  src/services/eventService.js
Labels: 💡 feature, 🔥 H-1, 🐶 KK

#6 [HEENDY-‪46-QR-participate] QR 인증 페이지
  package.json
  src/api/api.js
  src/api/request.js
  src/hooks/useEventParticipate.jsx
  src/hooks/useSocket.jsx
  src/index.js
  src/jsx/components/Alert/AlertComponent.jsx
  src/jsx/components/Modal/eventmodal/EventModal.jsx
  src/jsx/components/QrScanner/QRScannerComponent.jsx
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#7 [HEENDY-‪74-eventMember-list] QR인증 후 결과 반영
  .env
  .gitignore
  package-lock.json
  src/apis/api.jsx
  src/apis/request.jsx
  src/hooks/useEvents.jsx
  src/hooks/useGetEventMembers.jsx
  src/jsx/components/Cms/Content.jsx
Labels: 💡 feature, 🔥 H-1, 🐶 KK
