Repository hyundai-fruitfruit/admin-front, pull requests merged in 2024-03, with the labels that each got.

#8 [Heendy-35-login-etc] Admin 로그인 및 기타 수정
  src/jsx/components/Cms/Content.jsx
  src/jsx/components/Cms/Menu.jsx
  src/jsx/constant/theme.js
  src/jsx/layouts/nav/Menus2.jsx
  src/jsx/pages/Login.jsx
  src/services/AuthService.js
  src/store/actions/AuthActions.js
Labels: 💡 feature, 🐻 가브리엘, 🐾 refactor

#10 [HEENDY-98-deploy-admin] 어드민 프론트 S3 배포
  package.json
  src/services/couponService.js
  src/services/eventService.js
  src/setupProxy.js
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#9 [Heendy-91--statistics] 쿠폰 통계
  src/images/profile/small/sjsj.jpeg
  src/jsx/components/Cms/Content.jsx
  src/jsx/components/Dashboard/Elements/TopEventRates.js
  src/jsx/components/Dashboard/Home.jsx
  src/jsx/components/charts/CouponChart/CouponChartCss.css
  src/jsx/components/charts/CouponChart/CouponUsageBarChart.jsx
  src/jsx/components/charts/CouponChart/CouponUsageChart.jsx
  src/jsx/components/charts/UserChart/UserRegisterChart.jsx
  src/jsx/layouts/nav/Header.jsx
  src/services/couponService.js
Labels: 💡 feature, 🐞 fix, 🐻 가브리엘, 🐾 refactor
